server.port=8095
spring.application.name=consent-manager

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/consent_manager_db_fyp
spring.datasource.username=postgres
spring.datasource.password=postgresql123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Authentication JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
