package com.depa.consent.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Automatically cleans up stale PostgreSQL check constraints generated by Hibernate
 * on Enum columns when new enum values are added.
 */
@Component
@Order(1)
public class DatabaseConstraintCleaner implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseConstraintCleaner.class);
    private final JdbcTemplate jdbcTemplate;

    public DatabaseConstraintCleaner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        dropConstraintIfExists("audit_logs", "audit_logs_event_type_check");
        dropConstraintIfExists("users", "users_role_check");
        dropConstraintIfExists("users", "users_status_check");
        dropConstraintIfExists("organizations", "organizations_status_check");
        dropConstraintIfExists("user_invitations", "user_invitations_status_check");
        dropConstraintIfExists("email_verification_otps", "email_verification_otps_status_check");
        dropConstraintIfExists("data_requests", "data_requests_status_check");
        dropConstraintIfExists("consent_requests", "consent_requests_status_check");
        dropConstraintIfExists("consents", "consents_status_check");
        dropConstraintIfExists("access_grants", "access_grants_status_check");
    }

    private void dropConstraintIfExists(String tableName, String constraintName) {
        try {
            jdbcTemplate.execute("ALTER TABLE " + tableName + " DROP CONSTRAINT IF EXISTS " + constraintName);
            log.debug("Dropped check constraint '{}' from table '{}' if it existed.", constraintName, tableName);
        } catch (Exception e) {
            log.debug("Could not drop constraint '{}' from '{}': {}", constraintName, tableName, e.getMessage());
        }
    }
}
